"""modified_relationships_between_models

Revision ID: 5cefbf3625ee
Revises: daa9cffa86f9
Create Date: 2025-01-04 16:54:37.976190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cefbf3625ee'
down_revision: Union[str, None] = 'daa9cffa86f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'questionnaire', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_questions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_questions', type_='foreignkey')
    op.drop_constraint(None, 'questionnaire', type_='foreignkey')
    # ### end Alembic commands ###
