"""added_message_table_with_relation_user

Revision ID: c47b9f97219c
Revises: 9c99dd2db03c
Create Date: 2025-01-04 18:00:41.103093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47b9f97219c'
down_revision: Union[str, None] = '9c99dd2db03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
